### ISSUE TITLE
This repository and tim-reynolds/crop

### ISSUE THREAD

**Issue by firestorm23** [stojg/crop#22]
Why do they exist both ?

**Comment by stojg** [comment]
I will give a bit of background story. I read an excellent blog post about a project that intelligently tried to crop images automatically (http://blog.petersobot.com/a-use-for-smartphone-photos) in the dark ages (2012). So I wondered how if I could hack it in PHP, the language that I've used since since version 3. 

It was all a fun personal project, but it eventually got picked up on reddit and other places. At this time I was working with an open source framework so I decided that I would make an experience. Anyone that contributed to the project in some constructive way would be a contributor. This would give the person full push rights to this repository.

So it's quite interesting that some people actually actually made the effort of trying to contribute. You guys have the right mindset.

Now, obviously since this is open source and github makes it very easy to fork and make your own changes, there are  4 - 5 forks of this project at the moment.

I really promote this culture where people fork and make their own changes, so that in the end the best repo will prevail. I haven't contributed to this code base for a long time, but kept it up since some people seems to enjoy it.

I'm sure that Tim's version have a couple improvements and different way of providing some sort of entropy based cropping (maybe he actually got the algorithms correct, which I probably never did).

But alas, since this is open source anyone can fork and provide their version. There is no **official** repo if that's what you are looking for.

I hope that you will look at this code as an experiment, try it out, try Tim's fokl and see which one is better for your use case... And maybe you will fork it off, tweak it and make your own awesome version of it.
